<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>22413b4a-693f-45dd-aa84-384e3af7052b</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ConferenceBooking.BLL\ConferenceBooking.BLL.csproj" />
      <ProjectReference Include="..\ConferenceBooking.DAL\ConferenceBooking.DAL.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
    </ItemGroup>

</Project>
